export const FETCH_FROM_API_REQUEST='FETCH_FROM_API_REQUEST'
export const FETCH_FROM_API_SUCCESS = 'FETCH_FROM_API_SUCCESS'
export const FETCH_FROM_API_FAIL = 'FETCH_FROM_API_FAIL'

export const FETCH_GENRE_REQUEST = 'FETCH_GENRE_REQUEST'
export const FETCH_GENRE_SUCCESS = 'FETCH_GENRE_SUCCESS'
export const FETCH_GENRE_FAIL = 'FETCH_GENRE_FAIL'

export const FETCH_GENREMOVIES_REQUEST = 'FETCH_GENREMOVIES_REQUEST'
export const FETCH_GENREMOVIES_SUCCESS = 'FETCH_GENREMOVIES_SUCCESS'
export const FETCH_GENREMOVIES_FAIL = 'FETCH_GENREMOVIES_FAIL'

export const SEARCH_MOVIE_REQUEST = 'SEARCH_MOVIE_REQUEST'
export const SEARCH_MOVIE_SUCCESS = 'SEARCH_MOVIE_SUCCESS'
export const SEARCH_MOVIE_FAIL = 'SEARCH_MOVIE_FAIL'